package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class AutoGradedAssignment3 {
    public static void main(String[] args) {

        // Create a Scanner object to read input
        Scanner input = new Scanner(System.in);

        //Ask the user to enter the total students
        System.out.print("Enter the number of students: ");
        int numberOfStudents = input.nextInt(); // Read the number of students

        // Handle edge case if fewer than two students are entered
        if (numberOfStudents < 2) {
            System.out.println("Please enter at least two students.");
            return;
        }

        //Ask the user to enter the first student's name and score
        System.out.print("Enter the first student name: ");
        String student1 = input.next(); // Read the first student's name
        System.out.print("Enter the first student score: ");
        double score1 = input.nextDouble(); // Read the first student's score

        //Ask the user to enter the second student's name and score
        System.out.print("Enter the second student name: ");
        String student2 = input.next(); // Read the second student's name
        System.out.print("Enter the second student score: ");
        double score2 = input.nextDouble(); // Read the second student's score

        // If the second student has a higher score, swap the names and scores
        if (score1 < score2) {
            // Swap the names
            String nameSwap = student1;
            student1 = student2;
            student2 = nameSwap;

            // Swap the scores
            double scoreSwap = score1;
            score1 = score2;
            score2 = scoreSwap;
        }

        // Loop through the remaining students
        for (int i = 3; i <= numberOfStudents; i++) {
            // let's Ask the user to enter the next student's name and score
            System.out.print("Enter the next student name: ");
            String student = input.next(); // Read the next student's name
            System.out.print("Enter the next student score: ");
            double score = input.nextDouble(); // Read the next student's score

            // If the current student has a higher score than score1
            if (score > score1) {
                student2 = student1;
                score2 = score1;

                student1 = student;
                score1 = score;
            }
            // Else if the current student has a higher score than score2
            else if (score > score2) {
                // The current student becomes second highest
                student2 = student;
                score2 = score;
            }
        }

        // Step 8: Display the two students with the highest and second-highest scores
        System.out.println("Top two students:");
        System.out.println(student1 + "'s score is " + score1);
        System.out.println(student2 + "'s score is " + score2);
    }
}
