package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class AutoGradedAssignment6 {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        //Prompt the user to enter the first 12 of ISBN
        System.out.print("Enter the first 12 digits of an ISBN number as a string: ");
        String s = input.nextLine();

        //Check if the length of the input is 12
        if (s.length() != 12) {
            System.out.println(s + " is an invalid input."); // Change the message format
            return;  //return instead of System.exit(1)
        }

        //let's declare and initialize variable sum
        int sum = 0;

        // compute sum
        for (int num = 0; num < s.length(); num++) {
            int digit = s.charAt(num) - '0'; // Convert char to int
            if (num % 2 == 0) {
                // If num is even, add digit to sum
                sum += digit;
            } else {
                // If num is odd, add digit * 3 to sum
                sum += digit * 3;
            }
        }

        //Obtain checksum
        int checksum = 10 - (sum % 10);
        if (checksum == 10) {
            checksum = 0;
        }

        //Display the entire ISBN-13
        String isbn13 = s + checksum;
        System.out.println("The ISBN-13 number is " + isbn13);
    }
}
