package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class AutoGradedAssignment4 {

        public static void main(String[] args) {
            // let's create a Scanner object
            Scanner input = new Scanner(System.in);

            // Prompt the user to enter the loan amount
            System.out.print("Enter loan amount, for example 120000.95: ");
            double loanAmount = input.nextDouble(); // Read loan amount

            // Prompt the user to enter the number of years
            System.out.print("Enter number of years as an integer, for example 5: ");
            int numberOfYears = input.nextInt(); // Read loan period in years
            // let's print the header table
            System.out.printf("%-20s%-20s%-20s\n", "Interest Rate", "Monthly Payment", "Total Payment");
            for (double annualInterestRate = 5.0; annualInterestRate <= 8.0; annualInterestRate += 1.0 / 8) {
                // Step 3.4: Calculate monthly interest rate
                double monthlyInterestRate = annualInterestRate / 1200;

                //let's calculate monthly payment using the formula
                double monthlyPayment = loanAmount * monthlyInterestRate /
                        (1 - 1 / Math.pow(1 + monthlyInterestRate, numberOfYears * 12));

                // total payment
                double totalPayment = monthlyPayment * numberOfYears * 12;

                System.out.printf("| %-20.3f%% | %-20.2f | %-20.2f |\n", annualInterestRate, monthlyPayment, totalPayment);
            }
        }}




