package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class AutoGradedAssignment2 {

    public static void main(String[] args) {

                Scanner scanner = new Scanner(System.in);

                int max = 0;
                int count = 0;
                boolean containNumber = false; // Flag to check if any number was entered

                System.out.print("Enter an integer (0: for end of input): ");
                int number = scanner.nextInt(); // Read the first number

                // Check if the first number is 0
                if (number == 0) {
                    System.out.println("No numbers are entered except 0");
                    return; // exit if no valid input
                }

                // assign max to the first valid number
                max = number;
                count = 1;
                containNumber = true; // Set the flag to true

                // Loop to read subsequent numbers
                while (true) {
                    System.out.print("Enter an integer (0: for end of input): ");
                    number = scanner.nextInt();

                    if (number == 0) {
                        break; // Exit the loop if the input is 0
                    }

                    // Compare and update max and count
                    if (number > max) {
                        max = number; // Found a new maximum
                        count = 1; // Reset count to 1
                    } else if (number == max) {
                        count++; // Increment count if the number is equal to max
                    }
                }


                // Display results
                if (containNumber) {
                    System.out.println("The largest number is " + max);
                    System.out.println("The occurrence count of the largest number is " + count);
                }
            }
        }
