package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class AutoGradedAssignment5 {
    public static void main(String[] args) {

                // letis two variables where we store the number of vowels and consonants
                int numberOfVowels = 0;
                int numberOfConsonants = 0;

                // let's create a Scanner to read input
                Scanner input = new Scanner(System.in);
                // Prompt the user to enter a string
                System.out.print("Enter a string: ");
                String userInput = input.nextLine(); // the unput will be read as String

                // letis now loop through each character in the string
                for (int i = 0; i < userInput.length(); i++) {
                    char character = Character.toUpperCase(userInput.charAt(i)); // Convert character to uppercase

                    // it is time to check if character is vowels
                    if (character == 'A' || character == 'E' || character == 'I' || character == 'O' || character == 'U') {
                        numberOfVowels++; // Increase vowel count
                    }
                    // it is time to check if character is consonant
                    else if (Character.isLetter(character)) {
                        numberOfConsonants++; // Increase consonant count
                    }
                }

                // Step 4: Display the results
                System.out.println("The number of vowels is " + numberOfVowels);
                System.out.println("The number of consonants is " + numberOfConsonants);
            }
        }
