package AutoGeneratedExamesCahpter5;

// Scanner imported
import java.util.Scanner;
public class FutureInvestmentValueCalculation {
    // begin class
    public static void main(String[] args) {
    // Begin of main method
        /*
         * Full Name: Lhoucine ET TIHAMI
         * Statment of purpose: This program aims at calculating the future investment value based on
         * ---> the investment ammount, annual interest rate and number of years.
         * ---> the program relies on this formula:
         * futureInvestmentValue = investmentAmount * (1 + monthlyInterestRate)^(numberOfYears * 12
         */
    //Create Scanner object to read input
        Scanner scanner = new Scanner(System.in);
    //we are promting the user to enter the requested amount
        System.out.print("Enter investment amount: ");
    //we are storing the input in 'inveAmount'
        int invAmount = scanner.nextInt();
    // we are prompting again the user to enter the requested annual interest
        System.out.print("Enter annual interest rate: ");
    // we are storing the input in annualInterestRate
        double annualInterestRate = scanner.nextDouble();
    //we finally ask the user to enter the number of years
        System.out.print("Enter the number of years: ");
    //we store the input in numOfYears
        int numOfYears = scanner.nextInt();
    //we are then going to calculate the monthly interest rate
        double monthlyInterestRate = annualInterestRate /1200;
    //we calculate the future investment value relying on the formulas
        double futureInvestmentValue = invAmount * Math.pow(1 + monthlyInterestRate, numOfYears * 12);
    //we print the accumulated value rounded to two decimal num
        System.out.printf("Accumulated value is %.2f%n",  futureInvestmentValue);
    } //End of main method

}// end of class
