package AutoGeneratedExamesCahpter5;

import java.util.Scanner;

public class PointRectangle {

        public static void main(String[] args) {
            Scanner scanner = new Scanner(System.in);
            System.out.print("Enter a point with two coordinates: ");
            double x = scanner.nextDouble();
            double y = scanner.nextDouble();
            boolean isWithinRectangle = Math.abs(x) <= 5.0 && Math.abs(y) <= 2.5;
            System.out.println("Point (" + x + ", " + y + ") is " + (isWithinRectangle ?
                    "in " : "not in ") + "the rectangle");
        }
    }


