package AutoGeneratedExamesCahpter5;

public class practice {
    public static void main(String[] args) {

/*
Implement a method that takes a 2 dimensional integer array and a key as arguments,
and return the location (row and column index) of the key's last occurrence. As an example assume
 that I pass following array called numbers and key to my find method,

int[][] numbers = { {3, 4, 5}, {4, 7, 9}, {1, 4, 6, 8}, {2, 5} };

int key = 4

the method should return an array of two elements, that contains the location where value 4 appears last,
which is row 2 and column 1. Method should return -1,-1; if the key is not found.

public static int[] find(int[][] numbers, int key){

      // write code here.
}
 */

    }









}
