package classes.AssignmentModule2Chapter2;

import java.util.Scanner;

public class AutoGeneratedProjectAssignmentThree {

        public static void main(String[] args) {

            Scanner input = new Scanner(System.in);

            System.out.println("Enter a month in the year (e.g., 1 for Jan): ");
            int month = input.nextInt();
            System.out.println("Enter a year: ");
            int year = input.nextInt();
            String mnName;
            int dyInMn;

            switch (month) {
                case 1:
                    mnName = "January";
                    dyInMn = 31;
                    break;
                case 2:
                    mnName = "February";
                    if (isLeapYear(year)) {
                        dyInMn = 29;
                    } else {
                        dyInMn = 28;
                    }
                    break;
                case 3:
                    mnName = "March";
                    dyInMn = 31;
                    break;
                case 4:
                    mnName = "April";
                    dyInMn = 30;
                    break;
                case 5:
                    mnName = "May";
                    dyInMn = 31;
                    break;
                case 6:
                    mnName = "June";
                    dyInMn = 30;
                    break;
                case 7:
                    mnName = "July";
                    dyInMn = 31;
                    break;
                case 8:
                    mnName = "August";
                    dyInMn = 31;
                    break;
                case 9:
                    mnName = "September";
                    dyInMn = 30;
                    break;
                case 10:
                    mnName = "October";
                    dyInMn = 31;
                    break;
                case 11:
                    mnName = "November";
                    dyInMn = 30;
                    break;
                case 12:
                    mnName = "December";
                    dyInMn = 31;
                    break;
                default:
                    System.out.println("Invalid month entered.");
                    return;
            }
            System.out.println(mnName + " " + year + " has " + dyInMn + " days.");
        }

        public static boolean isLeapYear(int year) {
            return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
        }
    }

