package classes.AssignmentModule2Chapter2;

import java.util.Scanner;

public class AutoGeneratedProjectAssignmentFour {

        public static void main(String[] args) {

            Scanner nm = new Scanner(System.in);

            // Correct the prompts for better clarity
            System.out.println("Enter year (e.g., 2012): ");
            int year = nm.nextInt();
            System.out.println("Enter month (1-12): ");
            int month = nm.nextInt();
            System.out.println("Enter the day of the month (1-31): ");
            int dyMonth = nm.nextInt();

            // Adjust January and February
            if (month == 1) {
                month = 13;
                year = year - 1;
            } else if (month == 2) {
                month = 14;
                year = year - 1;
            }

            // Compute j and k
            int j = year / 100;
            int k = year % 100;

            // Apply Zeller's formula
            int h = (dyMonth + (26 * (month + 1)) / 10 + k + k / 4 + j / 4 + 5 * j) % 7;

            // Map h to the day of the week
            String weekDays;
            switch (h) {
                case 0: weekDays = "Saturday"; break;
                case 1: weekDays = "Sunday"; break;
                case 2: weekDays = "Monday"; break;
                case 3: weekDays = "Tuesday"; break;
                case 4: weekDays = "Wednesday"; break;
                case 5: weekDays = "Thursday"; break;
                case 6: weekDays = "Friday"; break;
                default: weekDays = "Not valid day"; break;
            }

            // Output the result
            System.out.println("Day of the week is " + weekDays);
        }
    }


