package classes.AssignmentModule2Chapter2;

import java.util.Scanner;

public class AutoGeneratedProjectAssignmentTwo {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
// we will promt the user to enter a, b, c , d, e, f
        System.out.println("Enter a, b, c, d, e, f: ");
        double a = scanner.nextDouble();
        double b = scanner.nextDouble();
        double c = scanner.nextDouble();
        double d = scanner.nextDouble();
        double e = scanner.nextDouble();
        double f = scanner.nextDouble();
        // let's compute detA
        double detA = a * d-b * c;
        //let's test if deta is 0
        if (detA == 0){
            System.out.println("The equation has no solution.");
        }else {
            // let's compute x and y and display the result
            double x = (e * d - b * f) / detA;
            double y = (a * f - e * c) / detA;
            System.out.println("x is " + ((x == (int)x) ? (int)x :x) +
                    " and y is " + ((y == (int)y) ? (int) y : y));
        }
    }
}
