package classes.AssignmentModule2Chapter2;

import java.util.Scanner;

public class AutoGeneratedAssignment {

    public static void main(String[] args) {


        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter a point with two coordinates: ");
        int x = scanner.nextInt();
        int y = scanner.nextInt();
         // let's now apply the selection to check if point isnide the rectangle as the hint shows
        if(x <= 5 && x >= -5 && y <= 2.5 && y >= -2.5){
            System.out.println("Point (" + x + " , " + y + ") is in the rectangke");
        }else {
            System.out.println("Point (" + x + " , " + y + ") is not in the rectangke");
        }
    }
}
