package AutoGradedChapter6;
import java.util.Scanner;
public class AutoGeneratedAssignment4 {

        // Method to convert milliseconds to hours, minutes, and seconds
        public static String convertMillis(long millis) {
            long totalSeconds = millis / 1000, totalMinutes = totalSeconds / 60, hours = totalMinutes / 60;
            long seconds = totalSeconds % 60, minutes = totalMinutes % 60;
            // Return the formatted time as hours:minutes:seconds
            return hours + ":" + minutes + ":" + seconds;
        }
        //Main method
        public static void main(String[] args) {
            //Prompt the user to enter a value for milliseconds
            Scanner input = new Scanner(System.in);
            System.out.print("Enter time in milliseconds: ");
            long totalMillis = input.nextLong();

            //Invoke convertMillis(totalMillis) and store the result
            String time = convertMillis(totalMillis);

            //Display the converted time string
            System.out.println(time);
        }
    }
