package AutoGradedChapter6;

import java.util.Scanner;
public class AutoGeneratedassignment1 {
    // create method to count future investment rate
    public static double futureInvestmentValue(double investmentAmount, double monthlyInterestRate, int years){
        return investmentAmount * Math.pow((1 + monthlyInterestRate), years * 12);
    }
    public static void main(String[] args) {
        // scanner object
        Scanner scanner = new Scanner(System.in);
        // promt the user to enter the investment amount
        System.out.print("The amount inevested: ");
        double investmentAmount = scanner.nextDouble();
        // promt the user to enter the annual interest rate
        System.out.print("Annual interest rate: ");
        double annualInterestRate= scanner.nextDouble();

        // convert annual interest rate to monthly
        double monthlyInterestRate= annualInterestRate / 1200;

        System.out.printf("%-10s %20s\n", "Years", "Future Value");

        for (int year= 1; year <=30; year++){
            double futureValue = futureInvestmentValue(investmentAmount, monthlyInterestRate,year);
            System.out.printf("%-10d %20.2f\n", year, futureValue);
        }

    }
}
