package AutoGradedChapter6;
import java.util.Scanner;
public class AutoGeneratedAssignment5 {
        // Method to format the integer with the specified width
        public static String format(int number, int width) {
            // Convert the number to a string
            String result = number + "";
            //Obtain the number of digits in the number
            int numberOfDigits = result.length();

            // dd 0s before the result to match the width, if needed
            for (int i = 1; i <= width - numberOfDigits; i++) {
                result = "0" + result;
            }

            //Return the formatted result
            return result;
        }
        // Main method
        public static void main(String[] args) {
            Scanner input = new Scanner(System.in);
            // Prompt the user to enter an integer number
            System.out.print("Enter an integer: ");
            int number = input.nextInt();
            // Prompt the user to enter an integer width
            System.out.print("Enter the width: ");
            int width = input.nextInt();
            // Invoke format(number, width) and display the result
            String formatNum = format(number, width);
            System.out.println("The formatted number is " + formatNum);
        }
    }
