package AutoGradedChapter6;

public class AutoGeneratedAssignment2 {


    // Method to calculate the sum of the series
    public static double m(int i) {
        // Declare and initialize sum
        double sum = 0.0;
        //  Add k / (k + 1.0) to sum for each k from 1 to i
        for (int k = 1; k <= i; k++) {
            // Using 1.0 to ensure double division
            sum += k / (k + 1.0);
        }
        //Return the sum
        return sum;
    }
    public static void main(String[] args) {
        //Display the header of the table using printf
        System.out.printf("%-10s%-10s\n", "i", "m(i)");

        //  For loop to display i and the result from invoking m(i)
        for (int i = 1; i <= 20; i++) {
            System.out.printf("%-10d%-10.4f\n", i, m(i));
        }
    }
}